<a href="https://colab.research.google.com/github/Shahzodbey/data_science_mohirdev/blob/main/indexlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 100, 10)
arr[1]

20

## Indexlash

In [4]:
arr[3:5] # arr ni 3 dan 5 gacha elementlarini kesadi, bunda 5 ozi kirmaydi.

array([40, 50])

In [5]:
sliced_arr = arr[3:5]
sliced_arr

array([40, 50])

In [7]:
sliced_arr[:] = 0 # agar kesib olingan elementlarni ozgartirsak bu asosiy array ga ham ta'sir qiladi.
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [8]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1

array([40, 50])

In [11]:
sliced_arr1[:] = 1 # agar kesishda copy() dan foydalansak asosiy array o'zgarmaydi.
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2[-1,:] # 2 olchamli array larni kesishda row va column indexini beramiz

array([7, 8, 9])

In [19]:
arr2[2, -2:]

array([8, 9])

In [20]:
arr3 = np.arange(27).reshape(3, 3, 3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [25]:
arr3[1, :, 1] # agar 3d array bolsa layer row column ketma-ketligida beramiz

array([10, 13, 16])

In [26]:
arr3[1][:, 1] # list elementlaridek kesib olish

array([10, 13, 16])

In [28]:
arr3[2, :, 0]

array([18, 21, 24])

## Boolean indexlash

In [31]:
ismlar = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyorbek', 'Hasan', 'Javohir', 'Elyorbek'])
ismlar

array(['Hasan', 'Husan', 'Mirzabek', 'Elyorbek', 'Hasan', 'Javohir',
       'Elyorbek'], dtype='<U8')

In [33]:
data = np.random.randn(7, 4) # randn ga shape ni berib data oldik.
data

array([[ 0.44618237,  0.16227232,  0.9816614 ,  0.5259195 ],
       [-0.13249842,  0.58998188, -0.76867065,  1.37256217],
       [ 0.30307075,  0.37463983,  0.77651861,  0.78088023],
       [ 2.05114987,  1.99162582,  0.81463679,  0.63103198],
       [-1.74485675,  0.82667376,  0.492443  ,  0.35167432],
       [-0.51141529,  1.43566729,  0.85527238,  0.3900393 ],
       [-0.86176719, -0.79774308, -0.72657322,  2.03498687]])

In [35]:
ismlar == 'Hasan' # Hasan ga teng bolgan elemnent indexlarini True qilib qaytaradi.

array([ True, False, False, False,  True, False, False])

In [36]:
data[ismlar == 'Hasan'] # Hasan ga tegishli ma'lumotlarni olish

array([[ 0.44618237,  0.16227232,  0.9816614 ,  0.5259195 ],
       [-1.74485675,  0.82667376,  0.492443  ,  0.35167432]])

In [37]:
data[ismlar == 'Husan']

array([[-0.13249842,  0.58998188, -0.76867065,  1.37256217]])

In [40]:
data[ismlar=='Hasan', -2:] # Hasanga tegishli oxirgi 2 ustundagi ma'lumotlarni kesish

array([[0.9816614 , 0.5259195 ],
       [0.492443  , 0.35167432]])

In [42]:
data[ismlar == 'Husan', :3] # Husan ga tegishli birinchi 3 ustunni kesib olish

array([[-0.13249842,  0.58998188, -0.76867065]])

In [48]:
data[ismlar=='Hasan', :2]

array([[ 0.44618237,  0.16227232],
       [-1.74485675,  0.82667376]])

In [49]:
data[ismlar != 'Hasan'] # Hasan dan tashqari barcha ma'lumotlar

array([[-0.13249842,  0.58998188, -0.76867065,  1.37256217],
       [ 0.30307075,  0.37463983,  0.77651861,  0.78088023],
       [ 2.05114987,  1.99162582,  0.81463679,  0.63103198],
       [-0.51141529,  1.43566729,  0.85527238,  0.3900393 ],
       [-0.86176719, -0.79774308, -0.72657322,  2.03498687]])

In [51]:
data[~(ismlar == 'Hasan')] # ~ orqali shartni teskari qilib olish

array([[-0.13249842,  0.58998188, -0.76867065,  1.37256217],
       [ 0.30307075,  0.37463983,  0.77651861,  0.78088023],
       [ 2.05114987,  1.99162582,  0.81463679,  0.63103198],
       [-0.51141529,  1.43566729,  0.85527238,  0.3900393 ],
       [-0.86176719, -0.79774308, -0.72657322,  2.03498687]])

In [59]:
ismlar

array(['Hasan', 'Husan', 'Mirzabek', 'Elyorbek', 'Hasan', 'Javohir',
       'Elyorbek'], dtype='<U8')

In [62]:
mask = (ismlar == 'Husan') | (ismlar == 'Javohir') # birnechta shart berish uchun | or degan ma'noni beradi.

In [65]:
data[mask] # mask orqali Husan va Javohir ga tegishli ma'lumotlarni oldik.

array([[-0.13249842,  0.58998188, -0.76867065,  1.37256217],
       [-0.51141529,  1.43566729,  0.85527238,  0.3900393 ]])

In [69]:
mask = data<0 # data dagi 0 dan kichik elementlar indexlarini olish

In [70]:
data[mask] = 0 # 0 dan kichik elementlarni 0 ga tenglash

In [71]:
data

array([[0.44618237, 0.16227232, 0.9816614 , 0.5259195 ],
       [0.        , 0.58998188, 0.        , 1.37256217],
       [0.30307075, 0.37463983, 0.77651861, 0.78088023],
       [2.05114987, 1.99162582, 0.81463679, 0.63103198],
       [0.        , 0.82667376, 0.492443  , 0.35167432],
       [0.        , 1.43566729, 0.85527238, 0.3900393 ],
       [0.        , 0.        , 0.        , 2.03498687]])