<a href="https://colab.research.google.com/github/Shahzodbey/data_science_mohirdev/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing library

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [4]:
my_list = list(range(100))
my_array = np.array(range(100))

In [8]:
%time for _ in range(10): [x**2 for x in my_list]

CPU times: user 351 µs, sys: 38 µs, total: 389 µs
Wall time: 395 µs


In [9]:
%time for _ in range(10): my_array**2

CPU times: user 55 µs, sys: 6 µs, total: 61 µs
Wall time: 66.5 µs


# numpy array

In [13]:
list1 = [3.5, 68, 15, 46, 2.5] # list
arr1 = np.array(list1) # array

In [14]:
tuple1 = (12, 15, 89, 56)
arr2 = np.array(tuple1)

## numpy o'lchami

In [15]:
arr1.ndim

1

In [16]:
arr2.ndim

1

In [17]:
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr3 = np.array(list2)

In [18]:
arr3.ndim

2

In [42]:
list3 = [
         [
          [1, 2, 3],
          [1, 2, 3]
          ],
         [
          [3, 4, 5],
          [3, 4, 5]
          ]
         ]
arr4 = np.array(list3)

In [43]:
arr4.shape

(2, 2, 3)

In [36]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
arr3.shape # qator va ustunlar soni

(2, 4)

In [38]:
arr3.size # array dagi elementlar soni

8

In [45]:
arr5 = np.zeros((2, 4, 2)) # zeros yordamida array hosil qilish
arr5

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [46]:
arr6 = np.ones((3, 2, 4)) # shape ni tuple ko'rinishida berish kerak.
arr6

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
arr7 = np.arange(2, 45, 3) # arange yordamida array h.q
arr7

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [50]:
arr8 = np.arange(45) # agar faqat bitta son kiritilsa osha songacha 1 qadamdan osuvchi array h.b
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])